Notebook[{Cell[
CellGroupData[{Cell[
BoxData[DynamicModuleBox[{Set[Typeset`querydata$$,
Association["query" -> "2^100","assumptions" -> {},"parse" -> Defer[Power[2,100]],
"inputpredictions" -> {},"otherpredictions" -> {"FullResults"},"allassumptions" -> {},
"summarizeassumptions" -> FrontEnd`SuppressEvaluationHash[Automatic],"summarizepredictions" -> FrontEnd`SuppressEvaluationHash[
True]]],Set[Typeset`update$$,FrontEnd`SuppressEvaluationHash[1]]},DynamicBox[ToBoxes[
AlphaIntegration`NaturalLanguageInputBoxes[1,Typeset`querydata$$,Typeset`update$$],
StandardForm],TrackedSymbols -> {}],RuleDelayed[DynamicModuleValues,{}],BaseStyle -> {Deployed -> True},
ExpressionUUID -> "a16fc9b3-12a5-4c00-9c1b-ec133174af68"]],"DeployedNLInput",PrivateCellOptions -> {"CellSettings" -> {"HideDetails" -> FrontEnd`SuppressEvaluationHash[
False]}},ExpressionUUID -> "3c7f37e4-cf2d-4f9f-9f29-72250c1d344e"],Cell[
BoxData[
RowBox[{"2","^","100"}]],"DeployedWLInput",CellAutoOverwrite -> True,GeneratedCell -> True,
CellLabel -> "In[7]:=",ExpressionUUID -> "a59e4a7b-493a-4f9c-adc0-ed7c6389bc9c"],Cell[
BoxData[
FormBox["1267650600228229401496703205376",TraditionalForm],TraditionalForm],"Output",
CellLabel -> "Out[7]= ",ExpressionUUID -> "4c1eb55f-248f-4485-a9c1-27439a059b87"]},
Open],ExpressionUUID -> "864841aa-6f46-432e-98b6-9a6cb4640c33"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"DivisorSigma","[",RowBox[{"0",",","1267650600228229401496703205376"}],"]"}]],
"Input",NumberMarks -> False,CellLabel -> "In[8]:= ",ExpressionUUID -> "871c4099-5de6-44a9-8448-1ed069b1548c"],Cell[
BoxData[
FormBox["101",TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[8]= ",
ExpressionUUID -> "dee22385-57e9-4128-a7b4-b61d174eda46"]},Open],ExpressionUUID -> "87b04423-e20a-48d6-9ec4-5d68b593f947"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"PrimePi","[","101","]"}]],"Input",NumberMarks -> False,CellLabel -> "In[9]:= ",
ExpressionUUID -> "3380e367-475e-4212-9439-1140c5ebc513"],Cell[
BoxData[FormBox["26",
TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[9]= ",ExpressionUUID -> "fccb5986-eac3-45dc-bc2f-441176ba26ba"]},
Open],ExpressionUUID -> "ac72a8ce-df40-4fc8-820f-77bba2aa2360"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"DivisorSigma","[",RowBox[{"1",",","26"}],"]"}]],"Input",NumberMarks -> False,
CellLabel -> "In[10]:= ",ExpressionUUID -> "b102f486-1df4-4c13-a868-1a0731b58855"],Cell[
BoxData[
FormBox["42",TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[10]= ",
ExpressionUUID -> "2329b451-b7fc-4ceb-afe3-c54a73c666a5"]},Open],ExpressionUUID -> "54c4ea7f-f212-4136-bde6-0068f8b5a160"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"PrimePi","[","42","]"}]],"Input",NumberMarks -> False,CellLabel -> "In[11]:= ",
ExpressionUUID -> "4c4b8f9a-416c-42df-9ef8-e0a4d2f5644b"],Cell[
BoxData[FormBox["13",
TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[11]= ",ExpressionUUID -> "25489819-3a79-4754-b919-1aa082c868e8"]},
Open],ExpressionUUID -> "8e395c61-7231-430e-b874-92bb30060f62"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"Range","[","13","]"}]],"Input",NumberMarks -> False,CellLabel -> "In[12]:= ",
ExpressionUUID -> "3a84653f-2ad1-41a8-8bb3-87700488a74a"],Cell[
BoxData[FormBox[RowBox[
{"{",RowBox[{"1",",","2",",","3",",","4",",","5",",","6",",","7",",","8",",","9",",","10",",","11",",","12",",","13"}],"}"}],
TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[12]= ",ExpressionUUID -> "e00d31e1-4665-498a-9149-237b29b3bec0"]},
Open],ExpressionUUID -> "fa2e9cf4-10b3-41ff-ae08-3fff7f06a0cd"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"Last","[",RowBox[{"{",RowBox[{"1",",","2",",","3",",","4",",","5",",","6",",","7",",","8",",","9",",","10",",","11",",","12",",","13"}],"}"}],"]"}]],
"Input",NumberMarks -> False,CellLabel -> "In[13]:= ",ExpressionUUID -> "103338b8-a86e-4c80-99e5-2d17029d56ae"],Cell[
BoxData[
FormBox["13",TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[13]= ",
ExpressionUUID -> "fa3e8c31-6371-4d8b-a5c0-697971be6eb8"]},Open],ExpressionUUID -> "7b699a33-ecf2-445e-8ae3-128d547e6ff0"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"PrimePi","[","13","]"}]],"Input",NumberMarks -> False,CellLabel -> "In[14]:= ",
ExpressionUUID -> "d7cd25f9-ad07-4c72-a8f3-18c61abbb5b5"],Cell[
BoxData[FormBox["6",
TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[14]= ",ExpressionUUID -> "1e628554-6510-4384-b68d-a5c212c96a8b"]},
Open],ExpressionUUID -> "72cc092e-5142-4a07-a706-8dcdf45d6de3"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{RowBox[{"DivisorSigma","[",RowBox[{"1",",","6"}],"]"}],"\[Equal]",RowBox[
{"2"," ","6"}]}]],"Input",NumberMarks -> False,CellLabel -> "In[15]:= ",ExpressionUUID -> "6ecb84fb-4cd9-497a-9fa6-b34208bc3b45"],Cell[
BoxData[
FormBox["True",TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[15]= ",
ExpressionUUID -> "3051fcf5-0521-4f7f-bf64-5b1cdad8d9ea"]},Open],ExpressionUUID -> "9829db90-ab8d-4597-b755-5b9aef14367d"],Cell[
CellGroupData[
{Cell[
BoxData[DynamicModuleBox[{Set[Typeset`querydata$$,Association["query" -> "2 ^ 100 // N",
"assumptions" -> {"\"UnitClash\" -> {\"N\", {\"NormalUnits\"}}"},"parse" -> Defer[
Quantity[None,IndependentUnit["normal"]][Power[2,100]]],"inputpredictions" -> {},
"otherpredictions" -> {"FullResults"},"allassumptions" -> {XMLElement["assumptions",
{"count" -> "1"},{XMLElement["assumption",{"type" -> "Unit","word" -> "N","template" -> "Assuming normal for \"N\"${separator}Use ${desc} or ${pulldown} instead","count" -> "4","pulldown" -> "true","pulldownlabel" -> "more >>","pulldownlength" -> "2","default" -> "\"UnitClash\" -> {\"N\", {\"NormalUnits\", \"dflt\"}}"},
{XMLElement["value",{"name" -> "NormalUnits","desc" -> "normal","input" -> "\"UnitClash\" -> {\"N\", {\"NormalUnits\"}}"},
{}],XMLElement["value",{"name" -> "Newtons","desc" -> "newtons","input" -> "\"UnitClash\" -> {\"N\", {\"Newtons\"}}"},
{}],XMLElement["value",{"name" -> "Nights","desc" -> "nights","input" -> "\"UnitClash\" -> {\"N\", {\"Nights\"}}"},
{}],XMLElement["value",{"name" -> "Nepers","desc" -> "nepers","input" -> "\"UnitClash\" -> {\"N\", {\"Nepers\"}}"},
{}]}]}]},"summarizeassumptions" -> FrontEnd`SuppressEvaluationHash[Automatic],"summarizepredictions" -> FrontEnd`SuppressEvaluationHash[
True]]],Set[Typeset`update$$,FrontEnd`SuppressEvaluationHash[2]]},DynamicBox[ToBoxes[
AlphaIntegration`NaturalLanguageInputBoxes[1,Typeset`querydata$$,Typeset`update$$],
StandardForm],TrackedSymbols -> {}],RuleDelayed[DynamicModuleValues,{}],BaseStyle -> {Deployed -> True},
ExpressionUUID -> "4e1e72d0-113d-411b-8eb9-01510eb5298e"]],"DeployedNLInput",PrivateCellOptionsCellSettings -> {"HideDetails" -> FrontEnd`SuppressEvaluationHash[
False]},CellLabel -> "In[17]:= ",PrivateCellOptions -> {"CellSettings" -> {"HideDetails" -> FrontEnd`SuppressEvaluationHash[
False]}},ExpressionUUID -> "595f994f-6ee6-42ca-8fa1-b4e95dc4856c"],Cell[
BoxData[
RowBox[{TemplateBox[{InterpretationBox["\[InvisibleSpace]",1],RowBox[{FrameBox[StyleBox[
"\"normal\"",ShowStringCharacters -> False,StripOnInput -> False],FrameMargins -> 1,
FrameStyle -> GrayLevel[0.85`],BaselinePosition -> Baseline,RoundingRadius -> 3,StripOnInput -> False]}],"normal",RowBox[
{"IndependentUnit","[","\"normal\"","]"}]},"Quantity"],"[",RowBox[{"2","^","100"}],"]"}]],
"DeployedWLInput",CellAutoOverwrite -> True,GeneratedCell -> True,CellLabel -> "In[17]:=",
PrivateCellOptions -> {"CellSettings" -> {"UsageTags" -> {{"Quantity",1},{"None",1},{"IndependentUnit",1}}}},
ExpressionUUID -> "2a3f08a5-1522-4850-887e-0dea0e4737c8"],Cell[
BoxData[FormBox[RowBox[
{RowBox[{"(",TemplateBox[{InterpretationBox["\[InvisibleSpace]",1],RowBox[{FrameBox[
StyleBox["\"normal\"",ShowStringCharacters -> False,StripOnInput -> False],FrameMargins -> 1,
FrameStyle -> GrayLevel[0.85`],BaselinePosition -> Baseline,RoundingRadius -> 3,StripOnInput -> False]}],"normal",RowBox[
{"IndependentUnit","[","\"normal\"","]"}]},"QuantityTF",SyntaxForm -> Mod],")"}],"\[InvisibleApplication]",RowBox[
{"(","1267650600228229401496703205376",")"}]}],TraditionalForm],TraditionalForm],
"Output",CellLabel -> "Out[17]= ",ExpressionUUID -> "32b8a09c-3cea-4117-a90d-949baab29190"]},
Open],ExpressionUUID -> "3e81aed1-adb8-47c9-964b-c241478c9134"],Cell[
CellGroupData[
{Cell[
BoxData[DynamicModuleBox[{Set[Typeset`querydata$$,Association["query" -> "1 / 3 + 2 / 7",
"assumptions" -> {},"parse" -> Defer[Plus[Times[1,Power[3,-1]],Times[2,Power[7,-1]]]],
"inputpredictions" -> {{"InputNumber$NumberLinePlot",Predictions`Prediction[0.84`,
"plotting","plot numbers",Function[HoldComplete[NumberLinePlot[{Rational[1,3],Rational[
2,7]}]]]],Predictions`InInput},{"InputNumber$SubtractNumbers",Predictions`Prediction[
0.8200000000000001`,"arithmetic operations","",{{Row[{"subtract ",Pane[Style[HoldForm[
"2/7"],LineBreakWithin -> False],ImageSize -> {150},BaselinePosition -> Baseline]," from ",Pane[
Style[HoldForm["1/3"],LineBreakWithin -> False],ImageSize -> {150},BaselinePosition -> Baseline]}],Function[
HoldComplete[Plus[Times[1,Power[3,-1]],Times[-1,Times[2,Power[7,-1]]]]]]},{Row[{"subtract ",Pane[
Style[HoldForm["1/3"],LineBreakWithin -> False],ImageSize -> {150},BaselinePosition -> Baseline]," from ",Pane[
Style[HoldForm["2/7"],LineBreakWithin -> False],ImageSize -> {150},BaselinePosition -> Baseline]}],Function[
HoldComplete[Plus[Times[2,Power[7,-1]],Times[-1,Times[1,Power[3,-1]]]]]]}}],Predictions`InInput},{"InputNumber$AlternativeOperation",Predictions`Prediction[
0.8`,"arithmetic operations","multiply numbers",Function[HoldComplete[Times[Times[
1,Power[3,-1]],Times[2,Power[7,-1]]]]]],Predictions`InInput},{"InputNumber$SquareNumbers",Predictions`Prediction[
0.78`,"arithmetic operations","square numbers",Function[HoldComplete[Power[{Times[
1,Power[3,-1]],Times[2,Power[7,-1]]},2]]]],Predictions`InInput},{"InputNumber$SquareRootsOfNumbers",Predictions`Prediction[
0.77`,"arithmetic operations","square roots of numbers",Function[HoldComplete[{Sqrt[
Times[1,Power[3,-1]]],Sqrt[Times[2,Power[7,-1]]]}]]],Predictions`InInput},{"InputNumber$GCD",Predictions`Prediction[
0.74`,"arithmetic operations","greatest common divisor",Function[HoldComplete[GCD[
Times[1,Power[3,-1]],Times[2,Power[7,-1]]]]]],Predictions`InInput},{"InputNumber$LCM",Predictions`Prediction[
0.73`,"arithmetic operations","least common multiple",Function[HoldComplete[LCM[Times[
1,Power[3,-1]],Times[2,Power[7,-1]]]]]],Predictions`InInput},{"InputNumber$TestDivisiblity",Predictions`Prediction[
0.7`,"arithmetic operations","test divisibility",Function[HoldComplete[Divisible[
Times[1,Power[3,-1]],Times[2,Power[7,-1]]]]]],Predictions`InInput},{"InputNumber$CommonDenominator",Predictions`Prediction[
0.5`,"arithmetic operations","write fractions over a common denominator",Function[
HoldComplete[Plus[Times[7,Power[21,-1]],Times[6,Power[21,-1]]]]]],Predictions`InInput}},
"otherpredictions" -> {"StepByStep","FullResults"},"allassumptions" -> {},"summarizeassumptions" -> FrontEnd`SuppressEvaluationHash[
True],"summarizepredictions" -> FrontEnd`SuppressEvaluationHash[False]]],Set[Typeset`update$$,
FrontEnd`SuppressEvaluationHash[2]]},DynamicBox[ToBoxes[AlphaIntegration`NaturalLanguageInputBoxes[
1,Typeset`querydata$$,Typeset`update$$],StandardForm],TrackedSymbols -> {}],RuleDelayed[
DynamicModuleValues,{}],BaseStyle -> {Deployed -> True},ExpressionUUID -> "87ee2d39-8077-4a64-8352-3ba45b3616a7"]],
"DeployedNLInput",PrivateCellOptionsCellSettings -> {"HideDetails" -> FrontEnd`SuppressEvaluationHash[
False]},PrivateCellOptions -> {"CellSettings" -> {"HideDetails" -> FrontEnd`SuppressEvaluationHash[
False]}},ExpressionUUID -> "1cac2b18-da81-42ed-93aa-642e6851d6e6"],Cell[
BoxData[
RowBox[{RowBox[{"1","/","3"}]," ","+"," ",RowBox[{"2","/","7"}]}]],"DeployedWLInput",
CellAutoOverwrite -> True,GeneratedCell -> True,CellLabel -> "In[18]:=",ExpressionUUID -> "475363c5-3669-40db-bbf4-b77861399110"],Cell[
BoxData[
FormBox[FractionBox["13","21"],TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[18]= ",
ExpressionUUID -> "2a2410ac-6ecd-425d-a0b5-8a34b8c68bf3"]},Open],ExpressionUUID -> "31f14101-ee19-4f9b-bdae-c8980a76b347"],Cell[
CellGroupData[
{Cell[
BoxData[DynamicModuleBox[{Set[Typeset`querydata$$,Association["query" -> "NumberLinePlot[{1/3, 2/7}]",
"assumptions" -> {},"parse" -> Defer[NumberLinePlot[{Rational[1,3],Rational[2,7]}]],
"inputpredictions" -> {},"otherpredictions" -> {"FullResults"},"allassumptions" -> {},
"summarizeassumptions" -> FrontEnd`SuppressEvaluationHash[Automatic],"summarizepredictions" -> FrontEnd`SuppressEvaluationHash[
True]]],Set[Typeset`update$$,FrontEnd`SuppressEvaluationHash[0]]},DynamicBox[ToBoxes[
AlphaIntegration`NaturalLanguageInputBoxes[1,Typeset`querydata$$,Typeset`update$$],
StandardForm],RuleDelayed[TrackedSymbols,{}]],BaseStyle -> {Deployed -> True},RuleDelayed[
DynamicModuleValues,{}],ExpressionUUID -> "65a283d1-075d-457a-ab9e-00d144809e97"]],
"DeployedNLInput",CellLabel -> "In[19]:= ",PrivateCellOptions -> {"CellSettings" -> {"HideDetails" -> FrontEnd`SuppressEvaluationHash[
False]}},ExpressionUUID -> "6c903ba4-ab9b-4fdc-892b-1ded7e984373"],Cell[
BoxData[
RowBox[{"NumberLinePlot","[",RowBox[{"{",RowBox[{RowBox[{"1","/","3"}],","," ",RowBox[
{"2","/","7"}]}],"}"}],"]"}]],"DeployedWLInput",CellAutoOverwrite -> True,GeneratedCell -> True,
CellLabel -> "In[19]:=",PrivateCellOptions -> {"CellSettings" -> {"UsageTags" -> {{"NumberLinePlot",1}}}},
ExpressionUUID -> "fd361214-4266-4999-94cc-e922a4aa8afb"],Cell[
BoxData[FormBox[GraphicsBox[
{{RGBColor[0.24720000000000014`,0.24`,0.6`],PointSize[Medium],Directive[LABColor[
0.676094128119322`,0.4485405917061707`,0.7359231649869302`],AbsoluteThickness[1.6`]],{PointBox[
NCache[{Rational[1,3],1},{0.3333333333333333`,1}]]}},{RGBColor[0.6`,0.24`,0.4428931686004542`],PointSize[
Medium],Directive[LABColor[0.676094128119322`,0.4485405917061707`,0.7359231649869302`],
AbsoluteThickness[1.6`]],{PointBox[NCache[{Rational[2,7],1},{0.2857142857142857`,1}]]}}},
AxesLabel -> {None},Ticks -> {Automatic,Automatic},FrameTicks -> {{Automatic,Automatic},{Automatic,Automatic}},
PlotRange -> {{0.2857142857142857`,0.3333333333333333`},{0,1}},PlotRangePadding -> {{Scaled[
0.1`],Scaled[0.1`]},{0,1}},AspectRatio -> NCache[Times[Rational[1,10],Power[GoldenRatio,
-1]],0.06180339887498948`],AxesOrigin -> {Automatic,Automatic},Axes -> {True,False},
ImagePadding -> All,{}],TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[19]= ",
ExpressionUUID -> "fe83435d-ba58-47bc-b49f-4ae6e2b8ad5d"]},Open],ExpressionUUID -> "de438af1-2789-4ed6-bbf5-c69e8154bf6d"],Cell[
CellGroupData[
{Cell[
"\<NumberLinePlot[{1/3, 2/7}]\>","WolframAlphaLong",CellLabel -> "In[20]:= ",
ExpressionUUID -> "de545f94-1a02-43b6-80be-0b23fac1a0e9"],Cell[
BoxData[FormBox[NamespaceBox[
"WolframAlphaQueryResults",DynamicModuleBox[{Set[Typeset`q$$,"NumberLinePlot[{1/3, 2/7}]"],Set[
Typeset`opts$$,{AppearanceElements -> {"Warnings","Assumptions","Brand","Pods","PodMenus","Unsuccessful","Sources"}}],Set[
Typeset`elements$$,{"Warnings","Assumptions","Brand","Pods","PodMenus","Unsuccessful","Sources"}],Set[
Typeset`asyncpods$$,{}],Set[Typeset`nonpods$$,{}],Set[Typeset`initdone$$,FrontEnd`SuppressEvaluationHash[
True]],Set[Typeset`queryinfo$$,{"success" -> "false","error" -> "false",{"http://www.w3.org/XML/1998/namespace","space"} -> "preserve","numpods" -> "0","datatypes" -> "","timedout" -> "","timedoutpods" -> "","timing" -> "1.057","parsetimedout" -> "false","recalculate" -> "","id" -> "","parseidserver" -> "9","host" -> "https://www6b3.wolframalpha.com","server" -> "9","related" -> "","version" -> "2.6"}],Set[
Typeset`sessioninfo$$,{"TimeZone" -> -5.`,"Date" -> {2024,8,3,1,15,41.172762`8.367184979808771},"Line" -> 20,"SessionID" -> 28149781819687020032}],Set[
Typeset`showpods$$,{}],Set[Typeset`failedpods$$,{}],Set[Typeset`chosen$$,{}],Set[
Typeset`open$$,False],Set[Typeset`newq$$,"NumberLinePlot[{1/3, 2/7}]"]},DynamicBox[
ToBoxes[AlphaIntegration`FormatAlphaResults[Dynamic[{1,{},{},Typeset`chosen$$,Typeset`open$$,Typeset`elements$$,Typeset`q$$,Typeset`opts$$,Typeset`nonpods$$,Typeset`queryinfo$$,Typeset`sessioninfo$$,Typeset`showpods$$,Typeset`failedpods$$,Typeset`newq$$}]],
TraditionalForm],RuleDelayed[TrackedSymbols,{Typeset`showpods$$,Typeset`failedpods$$}]],
RuleDelayed[Initialization,If[And[Not[SameQ[Typeset`initdone$$,True]],Not[SameQ[Typeset`initdone$$,
FrontEnd`SuppressEvaluationHash[True]]]],CompoundExpression[Null,WolframAlphaClient`Private`doAsyncUpdates[
Hold[{}],Typeset`asyncpods$$,Dynamic[Typeset`failedpods$$]],Set[Typeset`asyncpods$$,
{}],Set[Typeset`initdone$$,FrontEnd`SuppressEvaluationHash[True]]]]],RuleDelayed[
DynamicModuleValues,{}],SynchronousInitialization -> False,ExpressionUUID -> "685b0297-83ee-4456-bf18-be92aaa9efe9"],
BaseStyle -> {Deployed -> True},Editable -> False,DeleteWithContents -> True,SelectWithContents -> True],
TraditionalForm],TraditionalForm],"Output",CellLabel -> "Out[20]= ",ExpressionUUID -> "8b9a794e-2e52-4edc-80c5-0a15aa6ace73"]},
Open],ExpressionUUID -> "d4ab848b-8586-4b6b-8efd-b3ba0a114a50"]},StyleDefinitions -> "WolframAlphaNotebook.nb",
FrontEndVersion -> "14.1 for Wolfram Cloud 1.69 (July 16, 2024)"]